### ISSUE TITLE
RayContext can not be imported from pyjava in Python3.8.10

### ISSUE THREAD

**Issue by AndieHuang** [allwefantasy/pyjava#18]
Env：
python version：3.8.10
pyjava version：0.2.8.8
ray version: 1.3.0

![image](https://user-images.githubusercontent.com/88999787/129652805-aa6a318e-6d38-4327-becf-69edbe476d5f.png)

**Comment by ckeys** [comment]
This issue is duplicated with #19 
So just close it and see how this issue will be tackled in the issue of #19
